const stack = [
  { name: 'Crawl4AI', role: '内容采集器', summary: '把网页变成干净 Markdown、链接、元数据和结构化字段。', color: 'cyan' },
  { name: 'Browser Use', role: '交互执行器', summary: '让智能体像人一样打开页面、点击、输入、翻页并观察结果。', color: 'violet' },
  { name: 'n8n', role: '流程控制面', summary: '负责定时、分支、重试、凭据、通知和任务运行记录。', color: 'orange' },
  { name: 'PandasAI + Python', role: '分析与领域层', summary: '负责确定性清洗、统计分析、自然语言问数与报告生成。', color: 'green' },
];

const records = [
  ['source', '来源站点或渠道'], ['url', '可追溯原始链接'], ['title', '标题'],
  ['published_at', '内容发布时间'], ['collected_at', '采集时间'], ['author', '作者/机构'],
  ['summary', '摘要'], ['content', '清洗后的正文'], ['keywords', '关键词数组'],
  ['entities', '公司、产品、人物等实体'], ['evidence', '原文证据片段'],
  ['content_hash', '去重指纹'], ['status', '采集/校验状态'],
];

const labs = [
  { n: '00', title: '固定运行环境', goal: '先消除依赖冲突。Browser Use 要求 Python ≥ 3.11，而 PandasAI 当前 README 声明 Python ≤ 3.11，因此统一选择 Python 3.11。', command: `py -3.11 -m venv .venv\n.\\.venv\\Scripts\\Activate.ps1\npython --version\npip install -U pip`, result: '终端显示 Python 3.11.x；项目目录出现 .venv。把 .venv 与 .env 加入 .gitignore。' },
  { n: '01', title: '跑出第一份网页 Markdown', goal: '只验证“输入 URL → 输出干净文本”，暂时不要接数据库、LLM 或 n8n。', command: `pip install -U crawl4ai\ncrawl4ai-setup\ncrawl4ai-doctor\n\n# smoke_crawl.py\nimport asyncio\nfrom crawl4ai import AsyncWebCrawler, CrawlerRunConfig, CacheMode\n\nasync def main():\n    config = CrawlerRunConfig(cache_mode=CacheMode.BYPASS)\n    async with AsyncWebCrawler() as crawler:\n        r = await crawler.arun("https://example.com", config=config)\n        print({"success": r.success, "status": r.status_code})\n        print(r.markdown.raw_markdown[:300])\n\nasyncio.run(main())`, result: `{'success': True, 'status': 200}\n# Example Domain\nThis domain is for use in illustrative examples...` },
  { n: '02', title: '只在必要时启用浏览器智能体', goal: '验证“任务 → 页面状态 → 结构化动作 → 浏览器执行 → 新状态”的循环。需要一个模型 API Key。', command: `pip install browser-use python-dotenv\n\n# .env（任选一种模型提供方；不要提交到 Git）\nBROWSER_USE_API_KEY=your-key\n\n# smoke_browser.py\nimport asyncio\nfrom browser_use import Agent, ChatBrowserUse\n\nasync def main():\n    agent = Agent(\n        task="打开 example.com，返回页面主标题；不要访问其他域名",\n        llm=ChatBrowserUse(model="bu-2-0-mini-preview"),\n        max_steps=5,\n    )\n    history = await agent.run()\n    print(history.final_result())\n\nasyncio.run(main())`, result: '你会看到逐步 action 日志，最终返回 “Example Domain”。真实项目里还要限制允许域名、动作和最大步数。' },
  { n: '03', title: '建立统一数据合同', goal: '不让两个采集器各说各话。所有输出先落到同一个 IntelItem，再进入分析层。', command: `# src/models/article.py\nfrom datetime import datetime\nfrom pydantic import BaseModel, HttpUrl\n\nclass IntelItem(BaseModel):\n    source: str\n    url: HttpUrl\n    title: str\n    published_at: datetime | None = None\n    collected_at: datetime\n    summary: str = ""\n    content: str\n    keywords: list[str] = []\n    entities: list[str] = []\n    evidence: list[str] = []\n    content_hash: str\n    status: str = "ok"`, result: 'data/normalized/items.jsonl 中每行都是可校验 JSON；缺少 url、title 或 content 时立即失败，不把脏数据留到报告阶段。' },
  { n: '04', title: '标准化与去重', goal: '先用确定性 Python 规则处理时间、URL 和指纹；LLM 只做语义补充。', command: `from hashlib import sha256\nfrom urllib.parse import urlsplit, urlunsplit\n\ndef canonical_url(url: str) -> str:\n    p = urlsplit(url)\n    return urlunsplit((p.scheme.lower(), p.netloc.lower(), p.path.rstrip('/'), '', ''))\n\ndef fingerprint(title: str, content: str) -> str:\n    body = ' '.join((title + ' ' + content).lower().split())\n    return sha256(body.encode('utf-8')).hexdigest()\n\n# 先按 canonical_url 去重，再按 content_hash 去重`, result: '输出 before_count、after_count、duplicate_rate，并把重复记录写入 duplicates.csv 方便人工复核。' },
  { n: '05', title: '用 n8n 编排整条流水线', goal: '让 n8n 管“何时做、失败怎么办、通知谁”，Python 管“具体怎么算”。', command: `docker volume create n8n_data\ndocker run -it --rm --name n8n -p 5678:5678 ^\n  -v n8n_data:/home/node/.n8n docker.n8n.io/n8nio/n8n\n\n# 浏览器打开 http://localhost:5678\n# Schedule Trigger → HTTP Request(采集服务) → IF(校验)\n# → Execute Sub-workflow(标准化/去重) → HTTP Request(分析服务)\n# → 生成报告 → 邮件/企业微信通知`, result: '执行记录中每个节点都有输入/输出；失败分支能记录 URL、错误类型和重试次数。Windows PowerShell 可把多行命令写成一行运行。' },
  { n: '06', title: '先 Pandas，后 PandasAI', goal: '先做可复现的基线统计，再允许自然语言生成分析代码；生成代码应在沙箱中运行。', command: `pip install pandas pandasai pandasai-litellm pandasai-docker\n\n# deterministic_metrics.py\nimport pandas as pd\ndf = pd.read_json("data/normalized/items.jsonl", lines=True)\ndf["day"] = pd.to_datetime(df["published_at"]).dt.date\nprint(df.groupby(["day", "source"]).size().rename("mentions"))\n\n# PandasAI 只用于探索性问数，生产指标仍保留上面的确定性代码\n# sandbox = DockerSandbox(); sandbox.start()\n# response = pai.DataFrame(df).chat("按来源总结近7天提及量变化", sandbox=sandbox)`, result: '先得到可复核的 mentions 表；之后再得到自然语言解释或图表。两者对不上时，以已测试的 Pandas 指标为准。' },
  { n: '07', title: '生成报告并做验收', goal: '报告不是一段 LLM 长文，而是“结论 + 证据 + 数据质量 + 可追溯链接”。', command: `report/\n├─ index.html          # 本期市场情报报告\n├─ assets/trend.svg    # 趋势图\n├─ data/items.csv      # 可复核明细\n├─ data/duplicates.csv # 去重审计\n└─ run.json            # 运行时间、版本、成功率、错误数\n\n验收门槛示例：\n采集成功率 ≥ 95%\n关键字段完整率 ≥ 98%\n每条结论至少 1 个 evidence + url\n重复率、失败 URL、运行耗时可见`, result: '用 10 个已知页面做黄金样本；更新代码后自动比对字段、计数和证据，最后才接入定时运行。' },
];

function CodeBlock({ children }: { children: string }) { return <pre><code>{children}</code></pre>; }

export default function Home() {
  return <main>
    <header className="topbar"><a className="brand" href="#top" aria-label="返回页面顶部"><span className="brand-mark">MI</span><span>Market Intel Lab</span></a><nav aria-label="页面导航"><a href="#architecture">架构</a><a href="#source-code">源码</a><a href="#labs">实战</a><a href="#roadmap">改造</a></nav><span className="version">源码导读 · 2026.08</span></header>

    <section className="hero" id="top"><div className="hero-grid"><div><div className="eyebrow">市场情报自动收集与报告系统</div><h1>从开源工具到可运行系统，<br />一步步看懂它的内核。</h1><p className="hero-copy">这不是一份工具清单。你会沿着真实调用链读源码，跑出每个中间产物，再把四个开源内核组合成可观测、可追溯、可扩展的市场情报流水线。</p><div className="hero-actions"><a className="primary-button" href="#labs">从实验 00 开始</a><a className="text-button" href="#source-code">先读源码地图 →</a></div></div><aside className="hero-note" aria-label="最终产物"><span className="mini-label">FINAL OUTPUT</span><strong>每天自动生成一份<br />可信的市场变化摘要</strong><ul><li>原始网页证据可回溯</li><li>失败与重复数据可审计</li><li>关键趋势有确定性指标支撑</li><li>HTML / CSV / 通知同步输出</li></ul></aside></div></section>

    <section className="section architecture" id="architecture"><div className="section-heading"><span>00 / SYSTEM MAP</span><h2>先把职责边界画清楚</h2><p>一条重要原则：采集、业务逻辑、编排和分析不要混在一起。工具可以替换，数据合同不能漂移。</p></div><div className="flow" aria-label="系统处理流程">{['信源 URL','采集路由','内容与证据','标准化 / 去重','分析 / 报告'].map((item,index)=><div className="flow-item" key={item}><span>{String(index+1).padStart(2,'0')}</span><strong>{item}</strong>{index<4&&<i aria-hidden="true">→</i>}</div>)}</div><div className="routing-grid"><article><span className="decision yes">优先</span><h3>能直接读取正文？</h3><p>交给 <b>Crawl4AI</b>。成本更低、速度更快、结果更稳定，也更容易做缓存与批量并发。</p></article><article><span className="decision maybe">必要时</span><h3>必须点击、登录或翻页？</h3><p>交给 <b>Browser Use</b>。它是昂贵的交互型执行器，不应成为所有网页的默认入口。</p></article><article><span className="decision control">统一</span><h3>何时运行、失败怎么办？</h3><p>交给 <b>n8n</b>；把具体清洗与计算保留在 Python 服务中，通过 HTTP 或子流程调用。</p></article></div></section>

    <section className="section stack-section"><div className="section-heading"><span>01 / RESPONSIBILITY</span><h2>五项技术，在系统里的真实位置</h2></div><div className="module-grid">{stack.map((item,i)=><article className={`module-card ${item.color}`} key={item.name}><div className="module-meta"><span>0{i+1}</span><em>{item.role}</em></div><h3>{item.name}</h3><p>{item.summary}</p></article>)}</div></section>

    <section className="section source-section" id="source-code"><div className="section-heading"><span>02 / SOURCE CODE ATLAS</span><h2>从入口读到输出：四条核心调用链</h2><p>下面的文件名对应当前官方 GitHub 仓库。建议按“入口 → 状态/配置 → 执行器 → 结果模型”的顺序读，不要从工具函数海洋开始。</p></div><div className="deep-dives">
      <details open><summary><span className="summary-index">01</span><span><b>Crawl4AI</b><small>网页 → HTML → 清洗 → Markdown / JSON</small></span><span className="expand">展开源码地图</span></summary><div className="detail-body"><div className="purpose"><h3>它做什么</h3><p>面向 LLM 与数据管道的异步网页抓取器。浏览器或 HTTP 获取 HTML 后，清理 DOM、生成 Markdown，并可用 CSS/XPath/LLM 策略抽取结构化 JSON。</p></div><div className="call-chain"><span>你的脚本</span><i>→</i><span>AsyncWebCrawler.arun()</span><i>→</i><span>crawler strategy</span><i>→</i><span>scraping strategy</span><i>→</i><span>markdown / extraction</span><i>→</i><span>CrawlResult</span></div><div className="source-columns"><div><h4>核心入口与模块</h4><ul className="file-list"><li><code>crawl4ai/__init__.py</code><span>对外导出 API</span></li><li><code>async_webcrawler.py</code><span><b>AsyncWebCrawler</b>、start / close / arun / arun_many</span></li><li><code>async_configs.py</code><span>BrowserConfig、CrawlerRunConfig、LLMConfig</span></li><li><code>content_scraping_strategy.py</code><span>DOM 清洗与正文提取</span></li><li><code>markdown_generation_strategy.py</code><span>Markdown 与过滤结果</span></li><li><code>extraction_strategy.py</code><span>CSS、XPath、正则、LLM 抽取</span></li><li><code>models.py</code><span>CrawlResult、MarkdownGenerationResult</span></li></ul></div><div><h4>市场情报项目的改造重点</h4><ol><li>先写站点适配器与字段 schema，不直接改爬虫核心。</li><li>原始 HTML、cleaned HTML、evidence、URL 同时留存。</li><li>按域名配置限速、重试、缓存与并发，尊重 robots.txt 和网站条款。</li><li>把内容哈希与来源时间放进输出，便于增量采集和审计。</li></ol><a className="source-link" href="https://github.com/unclecode/crawl4ai" target="_blank" rel="noreferrer">打开官方仓库 ↗</a></div></div></div></details>
      <details><summary><span className="summary-index">02</span><span><b>Browser Use</b><small>任务 → 页面状态 → 动作 → 新状态 → 完成</small></span><span className="expand">展开源码地图</span></summary><div className="detail-body"><div className="purpose"><h3>它做什么</h3><p>把“自然语言任务”变成浏览器动作。Agent 观察页面状态，让 LLM 选择结构化动作，Tools 执行点击、输入、滚动或提取，再进入下一轮观察。</p></div><div className="call-chain"><span>Agent.run()</span><i>→</i><span>BrowserSession 状态</span><i>→</i><span>DomService 序列化</span><i>→</i><span>LLM ActionModel</span><i>→</i><span>Tools.act()</span><i>→</i><span>history / done</span></div><div className="source-columns"><div><h4>核心入口与模块</h4><ul className="file-list"><li><code>browser_use/__init__.py</code><span>Agent、BrowserSession、Tools 等懒加载导出</span></li><li><code>agent/service.py</code><span><b>Agent</b>；run、step、上下文准备、动作执行</span></li><li><code>agent/views.py</code><span>AgentState、ActionResult、AgentHistory</span></li><li><code>browser/session.py</code><span>浏览器生命周期、导航、页面状态、CDP</span></li><li><code>dom/service.py</code><span>可访问性树与可操作 DOM 快照</span></li><li><code>tools/service.py</code><span>点击、输入、滚动、提取、截图等动作</span></li></ul></div><div><h4>市场情报项目的改造重点</h4><ol><li>用固定任务模板和结构化输出，避免自由漫游。</li><li>限制域名、动作、最大步数、超时和下载目录。</li><li>登录、发布、提交表单等高风险动作前加入人工确认。</li><li>保留每步状态与动作日志；循环或验证码出现时明确失败。</li></ol><a className="source-link" href="https://github.com/browser-use/browser-use" target="_blank" rel="noreferrer">打开官方仓库 ↗</a></div></div></div></details>
      <details><summary><span className="summary-index">03</span><span><b>n8n</b><small>触发器 → 节点图 → 执行引擎 → 运行数据</small></span><span className="expand">展开源码地图</span></summary><div className="detail-body"><div className="purpose"><h3>它做什么</h3><p>可视化工作流编排平台。编辑器保存“节点 + 连接”，CLI 启动服务并激活工作流，运行器把一次触发交给执行引擎，执行引擎沿图调度节点并保存每步结果。</p></div><div className="call-chain"><span>bin/n8n</span><i>→</i><span>CommandRegistry</span><i>→</i><span>Start.run()</span><i>→</i><span>WorkflowRunner.run()</span><i>→</i><span>WorkflowExecute.run()</span><i>→</i><span>IRun</span></div><div className="source-columns"><div><h4>核心入口与模块</h4><ul className="file-list"><li><code>packages/cli/bin/n8n</code><span>Node CLI 真正入口</span></li><li><code>cli/src/command-registry.ts</code><span>解析命令，默认选择 start</span></li><li><code>cli/src/commands/start.ts</code><span>初始化服务、节点、UI 与活动工作流</span></li><li><code>cli/src/workflow-runner.ts</code><span>一次执行的控制面与持久化</span></li><li><code>core/.../workflow-execute.ts</code><span>寻找起点、建立执行栈、调度节点</span></li><li><code>workflow/src/workflow.ts</code><span>节点、连接、表达式等图模型</span></li><li><code>frontend/editor-ui/src/main.ts</code><span>Vue 编辑器入口</span></li></ul></div><div><h4>市场情报项目的改造重点</h4><ol><li>不要 fork n8n 核心；版本化导出的 workflow JSON。</li><li>采集、清洗、分析拆成可测试 Python 服务或子工作流。</li><li>每个外部调用加入幂等键、错误分支、退避重试和告警。</li><li>API Key 放 Credentials，不放 Code 节点、JSON 或 Git。</li></ol><p className="license-note">注意：n8n 采用 fair-code / Sustainable Use License，是 source-available，不等同于标准 OSI 开源许可。</p><a className="source-link" href="https://github.com/n8n-io/n8n" target="_blank" rel="noreferrer">打开官方仓库 ↗</a></div></div></div></details>
      <details><summary><span className="summary-index">04</span><span><b>PandasAI + Python</b><small>问题 → 生成代码 → 校验 / 清理 → 执行 → 响应</small></span><span className="expand">展开源码地图</span></summary><div className="detail-body"><div className="purpose"><h3>它做什么</h3><p>PandasAI 给 DataFrame 增加自然语言分析能力；Python 则承担系统的领域模型、确定性清洗、去重、指标计算、存储接口与报告模板。后者才是你项目长期稳定的内核。</p></div><div className="call-chain"><span>DataFrame.chat()</span><i>→</i><span>Agent._process_query()</span><i>→</i><span>CodeGenerator</span><i>→</i><span>CodeExecutor / Sandbox</span><i>→</i><span>ResponseParser</span></div><div className="source-columns"><div><h4>PandasAI 核心模块</h4><ul className="file-list"><li><code>dataframe/base.py</code><span>DataFrame.chat() 入口</span></li><li><code>agent/base.py</code><span>对话状态、生成、执行与重试</span></li><li><code>core/code_generation/base.py</code><span>LLM 生成代码，再校验和清理</span></li><li><code>core/code_execution/code_executor.py</code><span>执行代码并读取 result</span></li><li><code>core/response/parser.py</code><span>number / string / dataframe / plot</span></li><li><code>sandbox/</code><span>隔离生成代码的执行环境</span></li></ul></div><div><h4>正确的改造顺序</h4><ol><li>先用 Pandas 写并测试固定指标，再用 PandasAI 做探索。</li><li>给列定义明确语义、单位、时间粒度和允许聚合方式。</li><li>生成代码放 Docker Sandbox；不要把密钥或源数据库暴露给执行环境。</li><li>LLM 不直接改源数据；所有输出标注查询、代码、数据版本。</li></ol><a className="source-link" href="https://github.com/sinaptik-ai/pandas-ai" target="_blank" rel="noreferrer">打开官方仓库 ↗</a></div></div></div></details>
    </div></section>

    <section className="section contract-section"><div className="section-heading"><span>03 / DATA CONTRACT</span><h2>真正需要稳定的是这一行数据</h2><p>工具升级、网页改版都不可避免。统一的 IntelItem 能把变化隔离在采集适配层，不让分析和报告同时崩掉。</p></div><div className="contract-layout"><div className="record-grid">{records.map(([key,description])=><div key={key}><code>{key}</code><span>{description}</span></div>)}</div><aside className="rule-card"><span className="mini-label">TRUST RULE</span><h3>没有证据，就不是情报。</h3><p>每条自动生成的判断至少保留一个原文 evidence 和一个可访问 URL。摘要可以重算，证据必须可回溯。</p></aside></div></section>

    <section className="section python-section"><div className="section-heading"><span>04 / YOUR CORE</span><h2>你自己的 Python 项目应该长这样</h2></div><div className="repo-layout"><CodeBlock>{`market-intel/\n├─ src/\n│  ├─ main.py                  # composition root：组装依赖并启动一次运行\n│  ├─ config.py                # 环境变量与站点配置\n│  ├─ collectors/\n│  │  ├─ crawl4ai_collector.py # 静态/可渲染页面\n│  │  └─ browser_collector.py  # 必须交互的页面\n│  ├─ models/article.py        # IntelItem 数据合同\n│  ├─ pipeline/normalize.py    # URL、时间、文本标准化\n│  ├─ pipeline/dedupe.py       # URL + 内容指纹去重\n│  ├─ analysis/metrics.py      # 确定性指标\n│  ├─ reporting/html_report.py # 报告模板\n│  └─ storage/repository.py    # 文件/数据库抽象\n├─ workflows/market-intel.json # n8n 导出并纳入版本控制\n├─ tests/                      # 黄金样本与回归测试\n├─ data/raw/                   # 原始证据，只追加\n└─ data/normalized/            # 可分析标准数据`}</CodeBlock><div className="repo-notes"><h3>核心入口是 <code>src/main.py</code></h3><p>它只负责组装配置、采集器、存储库和报告器。每个模块都可以单独测试，也能被 n8n 通过 CLI 或 HTTP 调用。</p><div className="anti-pattern"><b>不要这样做</b><span>把所有 Python 代码塞进 n8n Code 节点；把 LLM 摘要当作唯一数据；失败后直接重跑整批；只保存最终报告不保存原始证据。</span></div></div></div></section>

    <section className="section labs-section" id="labs"><div className="section-heading"><span>05 / HANDS-ON LABS</span><h2>8 个检查点，逐步跑出中间结果</h2><p>一次只引入一个变量。每个实验都有“目标、运行内容、预期结果”；预期不一致时停在当前层排错。</p></div><div className="lab-list">{labs.map((lab,index)=><details key={lab.n} open={index===0}><summary><span className="lab-number">{lab.n}</span><span><b>{lab.title}</b><small>{lab.goal}</small></span><span className="expand">查看实验</span></summary><div className="lab-body"><div><span className="mini-label">RUN</span><CodeBlock>{lab.command}</CodeBlock></div><aside><span className="mini-label">EXPECTED CHECKPOINT</span><p>{lab.result}</p></aside></div></details>)}</div><p className="compliance">采集前请确认目标网站允许自动访问；遵守 robots.txt、服务条款、个人信息保护要求与合理限速。不要绕过验证码、访问控制或付费墙。</p></section>

    <section className="section roadmap-section" id="roadmap"><div className="section-heading"><span>06 / MODIFICATION ROADMAP</span><h2>如果现在开始改造，优先级这样排</h2></div><div className="roadmap"><article><span>P0 · 可信数据</span><h3>数据合同、证据、去重</h3><p>先确保同一条信息不会重复、字段可验证、结论可追溯。没有这一层，后面的自动化只会更快地产生混乱。</p></article><article><span>P1 · 稳定运行</span><h3>站点适配、重试、观测</h3><p>给不同域名配置采集策略；记录耗时、状态码、字段缺失和失败截图；增量运行而不是全量重抓。</p></article><article><span>P2 · 分析价值</span><h3>指标、主题、异常变化</h3><p>先回答“发生了什么”，再让 LLM 解释“为什么可能发生”。每条推断和事实分开标记。</p></article><article><span>P3 · 自动交付</span><h3>n8n 定时、报告与通知</h3><p>最后再接定时和通知。对外发送前保留人工审批开关，避免错误报告自动扩散。</p></article></div></section>

    <section className="section metrics-section"><div className="section-heading"><span>07 / DEFINITION OF DONE</span><h2>项目“完成”不是能跑，而是可验证</h2></div><div className="metrics-grid"><div><strong>≥ 95%</strong><span>采集成功率</span></div><div><strong>≥ 98%</strong><span>关键字段完整率</span></div><div><strong>100%</strong><span>结论含证据链接</span></div><div><strong>&lt; 24h</strong><span>情报新鲜度</span></div></div><div className="done-list"><h3>最终验收清单</h3><ul><li>10 个黄金样本页面通过回归测试</li><li>静态与交互页面能正确路由</li><li>重复记录、失败 URL 和运行版本可审计</li><li>生成代码在隔离环境运行，密钥不落盘、不入 Git</li><li>报告中的数字可以从 CSV 与确定性指标代码复算</li><li>工作流 JSON、配置模板和 README 一起进入版本控制</li></ul></div></section>

    <section className="section sources-section"><div className="section-heading"><span>08 / PRIMARY SOURCES</span><h2>继续往源码深处走</h2></div><div className="source-cards"><a href="https://github.com/unclecode/crawl4ai" target="_blank" rel="noreferrer"><b>Crawl4AI</b><span>README · async_webcrawler.py · strategies · models</span></a><a href="https://github.com/browser-use/browser-use" target="_blank" rel="noreferrer"><b>Browser Use</b><span>agent · browser session · DOM · tools</span></a><a href="https://github.com/n8n-io/n8n" target="_blank" rel="noreferrer"><b>n8n</b><span>CLI · workflow model · execution engine · editor</span></a><a href="https://github.com/sinaptik-ai/pandas-ai" target="_blank" rel="noreferrer"><b>PandasAI</b><span>DataFrame · Agent · code generation · sandbox</span></a></div><p className="source-note">源码路径与快速开始命令按 2026-08-27 的官方仓库核对。项目更新可能改变 API；实际安装时请锁定版本并保存 requirements.txt / lockfile。</p></section>

    <footer><div><span className="brand-mark">MI</span><b>Market Intel Lab</b></div><p>先跑出证据，再自动化判断。</p><a href="#top">回到顶部 ↑</a></footer>
  </main>;
}
